### ISSUE TITLE
Subscribing to location changes might be a no-op.

### ISSUE THREAD

**Issue by mayconfsousa** [CharlesStover/use-react-router#11]
The following code works for me.
It could be an enhancement?

```ts
import { useContext } from 'react';

// @ts-ignore
import { __RouterContext, RouteComponentProps } from 'react-router';

export default () => useContext<RouteComponentProps>(__RouterContext);
```

**Comment by quisido** [comment]
That is what is happening now, see [line 18](https://github.com/CharlesStover/use-react-router/blob/master/src/use-react-router.ts#L18).

In addition to listening on the Context, `use-react-router` adds code to re-render the component when the location changes. This is to bypass the problems with [update blocking](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md) that `react-router` has.

If you could elaborate more on how your enhancement differs from this implementation, let me know. I'm not sure I understand fully your proposal.

**Comment by mayconfsousa** [comment]
For what I understand, the problem with ```updating blocking``` it's only about class components. Once that ```use-react-router``` is a hook and couldn't be used with class components, I don't think that we need to worry about that.

**Comment by quisido** [comment]
If I can get a unit test for re-rendering in response to location changes that bypasses scenarios where updates are usually blocked, I'd be more than happy to remove the unnecessarily pub-sub behavior.

**Comment by avindra** [comment]
The official hooks simply directly return the context:

https://github.com/ReactTraining/react-router/blob/bb9b4fdc597dc29b7451723a5351b6cd16d5c1be/packages/react-router/modules/hooks.js#L17-L28

And I can also confirm having shipped direct usage of the context to a widely used production app, that the "pub-sub" functionality you're looking for works "out of the box"
