### ISSUE TITLE
does not read updated parameteres

### ISSUE THREAD

**Issue by klaky** [CharlesStover/use-react-router#18]
using react-router work, but wiht user-react-router does not work.

 // if there is no 'personId' in query string than set '1' - ?personId=1
const urlParams = new URLSearchParams(location.search)
 const selectedPersonId = urlParams.get('personId')

  if (!selectedPersonId) {
    urlParams.set('personId', '1')
    history.push({ search: `?${urlParams}` })
  }

**Comment by quisido** [comment]
Closing as stale with no additional information. If this continues to be a blocker for you, bug reports can be handled in the React Router official hook implementation.

Thanks for the community feedback! 😊
