### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by chiefGui** [CharlesStover/use-react-router#19]
O.K., this is not an issue, actually. This is just a personal thank you for those who contributed for this hook, specially @CharlesStover which authored it.

To give you some context: we're already using hooks at the app I'm working on, and 'been facing some headaches because of `withRouter`. 1) I don't like the HOC design; 2) typing `withRouter` was quite a pain. So your library saved me a few stressful minutes (maybe hour(s)) of work.

Would love to make a donation so you, the author, could drink a beer on me!

Last but not least, have a great day!

**Comment by quisido** [comment]
I appreciate the kind words. You are more than welcome. 😊
