### ISSUE TITLE
impossible to get params using typescript

### ISSUE THREAD

**Issue by EvilSourcerer** [CharlesStover/use-react-router#22]
Running
```js
console.log(match.params);
```
returns this 
![image](https://user-images.githubusercontent.com/32974335/64070051-4b8f0b00-cc26-11e9-9a8f-72cd81449483.png)

but this happens when I try to use typescript
![image](https://user-images.githubusercontent.com/32974335/64070052-5ba6ea80-cc26-11e9-81ea-2a812b73da99.png)

**Comment by EvilSourcerer** [comment]
fixed it, for those who are wondering what to do

1. Create an interface
```ts
interface RouterParams {
    server: string
}
```

2. Cast params to the interface
```ts
console.log((match.params as RouterParams).server);
```

There we go, all fixed! :+1:

**Comment by quisido** [comment]
I believe this is the intended use for adding params to `match`:
`const { match } = useReactRouter<RouterParams>();`
