### ISSUE TITLE
Perhaps add to the docs official implementation?

### ISSUE THREAD

**Issue by expelledboy** [CharlesStover/use-react-router#23]
React Router lib has [builtin hooks](https://github.com/ReactTraining/react-router/blob/637204984d6e40b7f980ac7e7c14489c76907198/packages/react-router/docs/api/hooks.md) now. There is a [blog post](https://reacttraining.com/blog/reach-react-router-future/) which details the future of the API.

**Comment by quisido** [comment]
I agree that 5.1 should be a part of the documentation, but it's just not a priority to determine the optimal way of handling the documentation at this time. While I encourage people to use the first-party hooks, I don't want to deprecate this for users who are unable or unwilling to upgrade to 5.1 or refactor their existing code.

I'm closing this in favor of #24, as that was opened by the `react-router` maintainer and contains useful debugging information for anyone who runs into issues mixing packages.

I'll leave that issue open to encourage users to migrate if issues arise and to direct their feature requests to first party support going forward.

Thanks for your interest in this package and community engagement. 😊
