### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by martinduo** [CharlesStover/use-react-router#9]
I already have react-router-dom v5.0.0. I just added react-router v5.0.0 and "use-react-router" v1.0.5 to my current project. The project now fails immediately with this:

Failed to compile
./node_modules/hoist-non-react-statics/dist/hoist-non-react-statics.cjs.js
Error: ENOENT: no such file or directory, open 'C:\Users\Bruce\Dropbox\Projects\AcesTESTER\node_modules\hoist-non-react-statics\dist\hoist-non-react-statics.cjs.js'

Any ideas?

**Comment by quisido** [comment]
I know this is an old issue, but has it been resolved since the official release on 5.0.0 non-alpha? Or upgrading to the latest `use-react-router`? I am not positive that this is an error with `use-react-router` itself, and I do not have reproduction steps to help debug it.

**Comment by martinduo** [comment]
I've moved on apparently. I don't see react-router or use-react-router in my project.json and I'm using react-router-dom v4.3.1. I can't remember the circumstances of this problem. Sorry
